name: CI/CD

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: build xpi
      run: make
    - uses: actions/upload-artifact@master
      with:
        name: ToggleNativeTabBar.xpi
        path: ToggleNativeTabBar.xpi
